export const ALBUMS = [
    {
        id: 0,
        name: 'Delfin',
        imageL: require('../components/images/DelfinAlbum.jpg'),
        count: 3,
        date: 'July 2018',
        featured: true,
        featuredimage: '../assets/images/DelfinFeatured.jpg',
    },
    {
        id: 1,
        name: 'Felipe',
        imageL: require('../components/images/FelipeAlbum2.jpg'),
        count: 3,
        date: 'February 2019',
        featured: false,
    },
    {
        id: 2,
        name: 'Mario',
        imageL: require('../components/images/MarioAlbum.jpg'),
        count: 3,
        date: 'March 2021',
        featured: false,
    },
    {
        id: 3,
        name: 'London',
        imageL: require('../components/images/LondonAlbum.jpg'),
        count: 4,
        date: 'September 2018',
        featured: true,
        featuredimage: '/assets/images/LondonFeatured.jpg',
    },
    {
        id: 4,
        name: 'Sevilla',
        imageL: require('../components/images/SevillaAlbum.jpg'),
        count: 3,
        date: 'September 2018',
        featured: false,
    },
    {
        id: 5,
        name: 'New York',
        imageL: require('../components/images/NYCAlbum.jpg'),
        count: 4,
        date: 'March 2017',
        featured: false,
    },
    {
        id: 6,
        name: 'Yosemite',
        imageL: require('../components/images/YosemiteAlbum.jpg'),
        count: 4,
        date: 'December 2020',
        featured: true,
        featuredimage: '/assets/images/YosemiteAlbum.jpg',
    },
    {
        id: 7,
        name: 'Pinnacles',
        imageL: require('../components/images/PinnaclesAlbum.jpg'),
        count: 4,
        date: 'January 2020',
        featured: false,
    },
    {
        id: 8,
        name: 'Misc. Landscapes',
        imageL: require('../components/images/MiscAlbum.jpg'),
        count: 4,
        date: '2019 - 2021',
        featured: false,
    }
];
